/*
* generated by Xtext
*/
package qa.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import qa.xtext.services.QaGrammarAccess;

public class QaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected qa.xtext.parser.antlr.internal.InternalQaParser createParser(XtextTokenStream stream) {
		return new qa.xtext.parser.antlr.internal.InternalQaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "QATest";
	}
	
	public QaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
