/*
 * generated by Xtext
 */
package qa.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QaRuntimeModule extends qa.xtext.AbstractQaRuntimeModule {

}
