/*
 * generated by Xtext
 */
package qa.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QaUiModule extends qa.xtext.ui.AbstractQaUiModule {
	public QaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
