/*
* generated by Xtext
*/
package qa.xtext.ui.contentassist;

import qa.xtext.ui.contentassist.AbstractQaProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QaProposalProvider extends AbstractQaProposalProvider {

}
